
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jeffrey Thor
 */
public class GameStartedForm extends javax.swing.JFrame {

    /**
     * Creates new form GameStartedForm
     */
    public GameStartedForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new javax.swing.JLabel();
        enterNameLabel = new javax.swing.JLabel();
        characterNameText = new javax.swing.JTextField();
        selectCharacterLabel = new javax.swing.JLabel();
        warriorLabel = new javax.swing.JLabel();
        wizardLabel = new javax.swing.JLabel();
        looterLabel = new javax.swing.JLabel();
        warriorSelectButton = new javax.swing.JButton();
        wizardSelectButton = new javax.swing.JButton();
        looterSelectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        welcomeLabel.setText("Welcome to the Land Of Lerocia");

        enterNameLabel.setText("Please enter your name:");

        selectCharacterLabel.setText("And select your character:");

        warriorLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        warriorLabel.setText("Warrior");

        wizardLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        wizardLabel.setText("Wizard");

        looterLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        looterLabel.setText("Looter");

        warriorSelectButton.setText("Select");
        warriorSelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warriorSelectButtonActionPerformed(evt);
            }
        });

        wizardSelectButton.setText("Select");
        wizardSelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wizardSelectButtonActionPerformed(evt);
            }
        });

        looterSelectButton.setText("Select");
        looterSelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                looterSelectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(welcomeLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(warriorSelectButton)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(enterNameLabel)
                                        .addGap(30, 30, 30)
                                        .addComponent(characterNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(warriorLabel)
                                        .addGap(82, 82, 82)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(wizardLabel)
                                            .addComponent(wizardSelectButton))
                                        .addGap(78, 78, 78)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(looterSelectButton)
                                            .addComponent(looterLabel)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(selectCharacterLabel)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLabel)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterNameLabel)
                    .addComponent(characterNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(selectCharacterLabel)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(warriorLabel)
                    .addComponent(wizardLabel)
                    .addComponent(looterLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(warriorSelectButton)
                    .addComponent(wizardSelectButton)
                    .addComponent(looterSelectButton))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void warriorSelectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warriorSelectButtonActionPerformed
        // TODO add your handling code here:
        try{
            if(this.characterNameText.getText().length() < 3){
                throw new Exception();
            }
            else if(this.characterNameText.getText().length() > 12){
                throw new Exception();
            }
            Character character = new Warrior(this.characterNameText.getText(), "warrior");
            VillageWindow village = new VillageWindow();
            village.sendCharacter(character);
            village.updateStatLabels();
            village.setVisible(true);
            this.setVisible(false);
        } catch(Exception e){
            System.err.println("Empty name field");
            JOptionPane.showMessageDialog(null, "Name must contain 3-12 characters.", "alert", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_warriorSelectButtonActionPerformed

    private void wizardSelectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wizardSelectButtonActionPerformed
        // TODO add your handling code here:
        try{
            if(this.characterNameText.getText().length() < 3){
                throw new Exception();
            }
            else if(this.characterNameText.getText().length() > 12){
                throw new Exception();
            }
            Character character = new Wizard(this.characterNameText.getText(), "wizard");
            VillageWindow village = new VillageWindow();
            village.sendCharacter(character);
            village.updateStatLabels();
            village.setVisible(true);
            this.setVisible(false);
        } catch(Exception e){
            System.err.println("Empty name field");
            JOptionPane.showMessageDialog(null, "Name must contain 3-12 characters.", "alert", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_wizardSelectButtonActionPerformed

    private void looterSelectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_looterSelectButtonActionPerformed
        // TODO add your handling code here:
        try{
            if(this.characterNameText.getText().length() < 3){
                throw new Exception();
            }
            else if(this.characterNameText.getText().length() > 12){
                throw new Exception();
            }
            Character character = new Looter(this.characterNameText.getText(), "looter");
            VillageWindow village = new VillageWindow();
            village.sendCharacter(character);
            village.updateStatLabels();
            village.setVisible(true);
            this.setVisible(false);
        } catch(Exception e){
            System.err.println("Empty name field");
            JOptionPane.showMessageDialog(null, "Name must contain 3-12 characters.", "alert", JOptionPane.WARNING_MESSAGE);
        }    
    }//GEN-LAST:event_looterSelectButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameStartedForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameStartedForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameStartedForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameStartedForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameStartedForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField characterNameText;
    private javax.swing.JLabel enterNameLabel;
    private javax.swing.JLabel looterLabel;
    private javax.swing.JButton looterSelectButton;
    private javax.swing.JLabel selectCharacterLabel;
    private javax.swing.JLabel warriorLabel;
    private javax.swing.JButton warriorSelectButton;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JLabel wizardLabel;
    private javax.swing.JButton wizardSelectButton;
    // End of variables declaration//GEN-END:variables
}
