
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jeffrey Thor
 */
public class GameOfLegends extends javax.swing.JFrame {
    
    /**
     * Creates new form DisplayForm
     */
    public GameOfLegends() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newGameButton = new javax.swing.JButton();
        loadGameButton = new javax.swing.JButton();
        LandOfLerociaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game Of Legends");

        newGameButton.setText("New Game");
        newGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameButtonActionPerformed(evt);
            }
        });

        loadGameButton.setText("Load Game");
        loadGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadGameButtonActionPerformed(evt);
            }
        });

        LandOfLerociaLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LandOfLerociaLabel.setText("Land Of lerocia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loadGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(LandOfLerociaLabel)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(LandOfLerociaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(newGameButton)
                .addGap(18, 18, 18)
                .addComponent(loadGameButton)
                .addGap(136, 136, 136))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadGameButtonActionPerformed
        // TODO add your handling code here:
        Character character;
        String fileName = "savedGame.txt";
        // temporary variables to store information read form save file
        String name, type, specialName;
        int experience, level, maxHealth, health, gold, stageNum;
        int inventory[] = new int[4];
        // Skeleton for file input system from http://stackoverflow.com/questions/4716503/reading-a-plain-text-file-in-java
        try {
            FileReader fileReader = 
                new FileReader(fileName);

            BufferedReader bufferedReader = new BufferedReader(fileReader);
            String line;
            
            name = bufferedReader.readLine();
            type = bufferedReader.readLine();
            experience = Integer.parseInt(bufferedReader.readLine());
            level = Integer.parseInt(bufferedReader.readLine());
            maxHealth = Integer.parseInt(bufferedReader.readLine());
            health = Integer.parseInt(bufferedReader.readLine());
            gold = Integer.parseInt(bufferedReader.readLine());
            specialName = bufferedReader.readLine();
            stageNum = Integer.parseInt(bufferedReader.readLine());
            for(int i = 0; i < 4; i++){
                inventory[i] = Integer.parseInt(bufferedReader.readLine());
            }
            if("warrior".equals(type)){
                character = new Warrior(name, type);
            }
            else if("wizard".equals(type)){
                character = new Wizard(name, type);
            }
            else if("looter".equals(type)){
                character = new Looter(name, type);
            }
            else {
                System.err.println("Character type load error");
                character = new Character();
            }
            character.setStats(type, name, experience, level, health, maxHealth, gold, stageNum);
            for(int i = 0; i < 4; i++){
                character.inventory[i] = inventory[i];
            }
            VillageWindow village = new VillageWindow();
            village.sendCharacter(character);
            village.updateStatLabels();
            village.setVisible(true);
            this.setVisible(false);
            
            bufferedReader.close();         
        }
        catch(FileNotFoundException ex) {
            System.err.println("Unable to open file '" + fileName + "'");                
        }
        catch(IOException ex) {
            System.err.println("Error reading file '" + fileName + "'");
        }
    }//GEN-LAST:event_loadGameButtonActionPerformed

    private void newGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameButtonActionPerformed
        GameStartedForm newGameWindow = new GameStartedForm();
        newGameWindow.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_newGameButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameOfLegends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameOfLegends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameOfLegends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameOfLegends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameOfLegends().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LandOfLerociaLabel;
    private javax.swing.JButton loadGameButton;
    private javax.swing.JButton newGameButton;
    // End of variables declaration//GEN-END:variables
}
