/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jeffreythor
 */
public class Shop extends javax.swing.JFrame {
    private Character character;
    private VillageWindow village;
    /**
     * Creates new form Shop
     */
    public Shop() {
        initComponents();
    }
    
    public void sendCharacter(Character character){
        this.character = character;
    }
    
    public void sendVillage(VillageWindow village){
        this.village = village;
    }
    
    public void updateShop(){
        characterGold.setText(Integer.toString(character.getGold()));
        numPotions.setText(Integer.toString(character.inventory[0]));
        numStrongPotions.setText(Integer.toString(character.inventory[1]));
        numStrongerPotions.setText(Integer.toString(character.inventory[2]));
        numStrongestPotions.setText(Integer.toString(character.inventory[3]));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shopLabel = new javax.swing.JLabel();
        potion = new javax.swing.JLabel();
        strongPotion = new javax.swing.JLabel();
        strongerPotion = new javax.swing.JLabel();
        strongestPotion = new javax.swing.JLabel();
        buyPotion = new javax.swing.JButton();
        buyStrongPotion = new javax.swing.JButton();
        buyStrongerPotion = new javax.swing.JButton();
        buyStrongestPotion = new javax.swing.JButton();
        goldLabel = new javax.swing.JLabel();
        characterGold = new javax.swing.JLabel();
        ownedLabel = new javax.swing.JLabel();
        numPotions = new javax.swing.JLabel();
        numStrongPotions = new javax.swing.JLabel();
        numStrongerPotions = new javax.swing.JLabel();
        numStrongestPotions = new javax.swing.JLabel();
        leaveShop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        shopLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        shopLabel.setText("Shop");

        potion.setText("Potion (200)");

        strongPotion.setText("Strong Potion (400)");

        strongerPotion.setText("Stronger Potion (800)");

        strongestPotion.setText("Strongest Potion (2000)");

        buyPotion.setText("buy");
        buyPotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyPotionActionPerformed(evt);
            }
        });

        buyStrongPotion.setText("buy");
        buyStrongPotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyStrongPotionActionPerformed(evt);
            }
        });

        buyStrongerPotion.setText("buy");
        buyStrongerPotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyStrongerPotionActionPerformed(evt);
            }
        });

        buyStrongestPotion.setText("buy");
        buyStrongestPotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyStrongestPotionActionPerformed(evt);
            }
        });

        goldLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        goldLabel.setText("Gold:");

        ownedLabel.setText("owned");

        leaveShop.setText("Done");
        leaveShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveShopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(leaveShop)
                .addGap(69, 69, 69)
                .addComponent(shopLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(goldLabel)
                    .addComponent(strongPotion)
                    .addComponent(potion)
                    .addComponent(strongerPotion)
                    .addComponent(strongestPotion))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buyStrongerPotion, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(buyStrongPotion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buyPotion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buyStrongestPotion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(characterGold, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(numStrongerPotions, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numStrongPotions, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numPotions, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ownedLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numStrongestPotions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shopLabel)
                    .addComponent(leaveShop))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(goldLabel)
                    .addComponent(characterGold, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(ownedLabel)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numPotions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(potion)
                        .addComponent(buyPotion)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numStrongPotions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(strongPotion)
                        .addComponent(buyStrongPotion)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numStrongerPotions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(strongerPotion)
                        .addComponent(buyStrongerPotion)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numStrongestPotions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(strongestPotion)
                        .addComponent(buyStrongestPotion)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buyPotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyPotionActionPerformed
        // TODO add your handling code here:
        if(character.getGold() >= 200){
            character.addItem("potion");
            character.setGold(character.getGold()-200);
            updateShop();
        }
    }//GEN-LAST:event_buyPotionActionPerformed

    private void buyStrongPotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyStrongPotionActionPerformed
        // TODO add your handling code here:
        if(character.getGold() >= 400){
            character.addItem("strong potion");
            character.setGold(character.getGold()-400);
            updateShop();
        }
    }//GEN-LAST:event_buyStrongPotionActionPerformed

    private void buyStrongerPotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyStrongerPotionActionPerformed
        // TODO add your handling code here:
        if(character.getGold() >= 800){
            character.addItem("stronger potion");
            character.setGold(character.getGold()-800);
            updateShop();
        }
    }//GEN-LAST:event_buyStrongerPotionActionPerformed

    private void buyStrongestPotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyStrongestPotionActionPerformed
        // TODO add your handling code here:
        if(character.getGold() >= 2000){
            character.addItem("strongest potion");
            character.setGold(character.getGold()-2000);
            updateShop();
        }
    }//GEN-LAST:event_buyStrongestPotionActionPerformed

    private void leaveShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveShopActionPerformed
        // TODO add your handling code here:
        village.updateStatLabels();
        this.setVisible(false);
        village.setVisible(true);
    }//GEN-LAST:event_leaveShopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Shop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyPotion;
    private javax.swing.JButton buyStrongPotion;
    private javax.swing.JButton buyStrongerPotion;
    private javax.swing.JButton buyStrongestPotion;
    private javax.swing.JLabel characterGold;
    private javax.swing.JLabel goldLabel;
    private javax.swing.JButton leaveShop;
    private javax.swing.JLabel numPotions;
    private javax.swing.JLabel numStrongPotions;
    private javax.swing.JLabel numStrongerPotions;
    private javax.swing.JLabel numStrongestPotions;
    private javax.swing.JLabel ownedLabel;
    private javax.swing.JLabel potion;
    private javax.swing.JLabel shopLabel;
    private javax.swing.JLabel strongPotion;
    private javax.swing.JLabel strongerPotion;
    private javax.swing.JLabel strongestPotion;
    // End of variables declaration//GEN-END:variables
}
