/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jeffreythor
 */
public class StoryMode extends javax.swing.JFrame {
    VillageWindow village;
    Character character;
    /**
     * Creates new form StoryMode
     */
    public StoryMode() {
        initComponents();
    }
    
    public void sendVillage(VillageWindow village){
        this.village = village;
    }
    
    public void sendCharacter(Character character){
        this.character = character;
    }
    
    public void playStory(){
        if(character.getStageNum() == 1){
            storyStage.setText("Stage 1");
            storyText.setText("As you begin to leave the village, you come across a man standing on the side of the path. He begins to speak to you as you approach.\nMy name's Jack. Are you headed to the Lerocian Castle? I wouldn't recommend it. I've gotten word that they're not letting anyone near it today, not quite sure why. You'd be wasting your time to go, I'd say just turn around now.\nJack: No you say? I didn't want to have to do this, but I can't let you go any further.\nJack begins to charge you! You have no choice but to defend yourself!");
        }
        else if(character.getStageNum() == 2){
            storyStage.setText("Stage 2");
            storyText.setText("stage 2 story");
        }
        else if(character.getStageNum() == 3){
            storyStage.setText("Stage 3");
            storyText.setText("stage 3 story");
        }
        else if(character.getStageNum() == 4){
            storyStage.setText("Stage 4");
            storyText.setText("stage 4 story");
        }
        else if(character.getStageNum() == 5){
            storyStage.setText("Stage 5");
            storyText.setText("stage 5 story");
        }
        else if(character.getStageNum() == 6){
            storyStage.setText("Stage 6");
            storyText.setText("stage 6 story");
        }
        else{
            System.err.println("Stage selection error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        storyText = new javax.swing.JTextArea();
        storyStage = new javax.swing.JLabel();
        continueButton = new javax.swing.JButton();
        toVillageButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        storyText.setColumns(20);
        storyText.setRows(5);
        jScrollPane1.setViewportView(storyText);

        storyStage.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        storyStage.setText("Stage n");

        continueButton.setText("Continue");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        toVillageButton.setText("To Village");
        toVillageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toVillageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(storyStage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(toVillageButton)
                .addGap(57, 57, 57)
                .addComponent(continueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(storyStage)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(continueButton)
                    .addComponent(toVillageButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        // TODO add your handling code here:
        Battle battle = new Battle();
        Enemy enemy;
        switch (character.getStageNum()) {
            case 1:
                enemy = new Jack("jack", 3);
                break;
            case 2:
                enemy = new Thug("thug", 5);
                //enemy = new Brawler("brawler", 6);
                //enemy = new Hunter("hunter", 7);
                break;
            case 3:
                enemy = new Knight("knight1", 10);
                //enemy = new Knight("knight2, 11);
                break;
            case 4:
                enemy = new Orc("orc", 17);
                break;
            case 5:
                enemy = new Guardian("guardian1", 20);
                //enemy = new Guardian("guardian2", 20);
                //enemy = new Guardian("guardian3", 20);
                break;
            case 6:
                enemy = new KingJack("kingJack", 25);
                break;
            default:
                enemy = new Enemy();
                System.err.println("Stage selection error");
                break;
        }
        battle.sendEnemy(enemy);
        battle.sendCharacter(character);
        battle.sendVillage(village);
        battle.sendStory(this);
        battle.updateBattleStats();
        this.setVisible(false);
        battle.setVisible(true);
    }//GEN-LAST:event_continueButtonActionPerformed

    private void toVillageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toVillageButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        village.setVisible(true);
    }//GEN-LAST:event_toVillageButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StoryMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StoryMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StoryMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StoryMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StoryMode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continueButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel storyStage;
    private javax.swing.JTextArea storyText;
    private javax.swing.JButton toVillageButton;
    // End of variables declaration//GEN-END:variables
}
